version: '3.9'

services:
  mysql-auth:
    image: mysql:8.0
    container_name: mysql-auth
    environment:
      MYSQL_DATABASE: auth_db
      MYSQL_USER: chrono
      MYSQL_PASSWORD: chrono_pass
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - auth_data:/var/lib/mysql

  mysql-event:
    image: mysql:8.0
    container_name: mysql-event
    environment:
      MYSQL_DATABASE: event_db
      MYSQL_USER: chrono
      MYSQL_PASSWORD: chrono_pass
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3306"
    volumes:
      - event_data:/var/lib/mysql

  mysql-media:
    image: mysql:8.0
    container_name: mysql-media
    environment:
      MYSQL_DATABASE: media_db
      MYSQL_USER: chrono
      MYSQL_PASSWORD: chrono_pass
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3309:3306"
    volumes:
      - media_data:/var/lib/mysql

  minio:
    image: minio/minio:latest
    container_name: chrono-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server --console-address ":9001" /data

volumes:
  auth_data:
  event_data:
  media_data:
  minio_data:
