spring.application.name=gateway-service
server.port=8080

# Route vers auth-service
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**

# Route vers media-service
spring.cloud.gateway.routes[1].id=media-service
spring.cloud.gateway.routes[1].uri=http://localhost:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/media/**

# Route vers event-service
spring.cloud.gateway.routes[2].id=event-service
spring.cloud.gateway.routes[2].uri=http://localhost:8083
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/event/**

# Filtres par défaut pour les CORS et les cookies
spring.cloud.gateway.default-filters[0]=DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
spring.cloud.gateway.default-filters[1]=AddResponseHeader=Access-Control-Allow-Origin, http://localhost:4200
spring.cloud.gateway.default-filters[2]=AddResponseHeader=Access-Control-Allow-Credentials, true

# Logging
logging.level.org.springframework.cloud.gateway=DEBUG
