server.port=8082
spring.application.name=media-service

# Datasource
spring.datasource.url=jdbc:mysql://localhost:3309/media_db
# spring.datasource.username=chrono
# spring.datasource.password=chrono_pass
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT shared secret
jwt.secret=VerySecretKeyThatIsAtLeast256BitsLongToBeSecure123456!
